language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - sudo apt-get install -y awscli

install: true

script:
  - ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

deploy:
  provider: releases
  api-key:
    secure: TXedn0kc5TaLol+/Hl1RoOKvhucANcgUMqQw5FxE4wUJfqxbqT5fVeLVPjn9II8G1tgkB8v1zqG+wMk3e264/vhyf3IA5DBVj0UX5a4X/QfMCO2iQFBoQ+DRFBWCM1szPbfNxwbO2kzr+laX7t/fOBA+ESHPv6d6BLR1Ll0sZaX1re4hQBPT12fpdm+7rx1Peb1u/4j56dxiYMkI1qUbvYzxmS6EgBHO4LtXxNEpw9IPknUCecWCl6tRbKgg1Xsppm9/LQMn9Xc64o7GLE+BD+rBy93QnCZJUHNcUZvK+D0TXGfRxffpkYs6ZBtU9PjSv/603a6N6gmrnyi/m9NDBLpbnRtvBIzRj0CupFFdeAe6pfhEdmQ4HbJGPxdb7BOndOc+waAI6ObT+3qCg138h8mbBW12O0pQRm+0XXrTM5aVWqklMKyprPK2q3GeJt1pBrBZcQpXw6MqG9aF95uz7L2cZ9sfVM4eVGR/diLq+9bSgieR3ZEqi/R0QvrgcGe+V5CuT+O3DxzBZbpdlvxB7f3EKEv23nJFwR7d/i54rCi/GNKhIBAt3vItm6dz5tX8PyyPAfNaRos0+wrmLVxwPFWVPPmttu1zNPRvmia8rv7stG94W5/4Z43DVQYjkbLYU6vND9ZoPtqKC82NuMePKcwKKW2w3XKr2JjRmsoulMc=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    tags: true