language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - sudo apt-get install -y awscli

install: true

script:
  - ./gradlew build

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

deploy:
  provider: releases
  api_key:
    secure: aeAFoTMQr5T9FmJ2aKKKGfb4GngTt6aMxj6veWL/aA4E6DB07eQUPQv/kYexBuv+Ax7ZBemOwqtJ6iQ997ra7VUaqY6M0XhcpAMDKxbp9DhbhKSO20s45nOt7A0xhhvSsV3W8MhKPZcSxVkEr7MoOAxEunuuy/ougQQ0YO+HTRsjKFaoY2cFUzDaomjnzu5+Ea88J1K08qvlUM7HZofQwPUrGoywZ5mL058eJK4TUrZOI83beHpi22XVHr350vaPd+ZwP+W4AbYp0JDaxM3KUdeFFML1pAvtmZaEey/JGRE50ub9R5uw4NoCTP+mHKTWF3Ihb/7pQIIkEBuHaHrU7lu1ZFcEPSaOuYzAYT333/Pe41V8JiQHVxgYt/Jf900MlhlIYk31/Yfs+k/hqpcweOgNwQPfCJQAJyv1oQxe6CsyM7s9PhGPxqfSmYRFvE2UO3t+LI4DP/f9r4m7noygOUc1qclltk3vqfcnETL4KkBohBA9aJ+AHhol8zcbUSoMHFHIOAievA9xeMmTac4mH9oZjnBMcEiq9cmYzY/u6jVKbOfPKHZdEySFNDOvNoWuLJMfk5x5Lcrszc4JMULAP5MuUUxOAYKzN7IF1/v0tB98RE52GS/OY0iDbqkXdLiXiLb5HYw+czn2OuZ0B+aVJ7lQg+Qw2+6VvWAgJdIK08c=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    tags: true
